from src.config import (
    REQUEST_DELAY_SECONDS,
    RETRY_COUNT,
    TIMEOUT,
    HISTORY_RETENTION_DAYS,
)

print(f"REQUEST_DELAY_SECONDS:  {REQUEST_DELAY_SECONDS}")
print(f"RETRY_COUNT:            {RETRY_COUNT}")
print(f"TIMEOUT:                {TIMEOUT}")
print(f"HISTORY_RETENTION_DAYS: {HISTORY_RETENTION_DAYS}")